const constants = {
    ADD_CATEGORY: 'ADD_CATEGORY',
    ADD_POST: 'ADD_POST',
    ADD_COMMENT: 'ADD_COMMENT',
    DELETE_POST: 'DELETE_POST',
    DELETE_COMMENT: 'DELETE_COMMENT',
    EDIT_POST: 'EDIT_POST',
    EDIT_COMMENT: 'EDIT_COMMENT',
    POST_VOTE_SCORE: 'POST_VOTE_SCORE',
    COMMENT_VOTE_SCORE: 'COMMENT_VOTE_SCORE',
    SORT_POSTS: 'SORT_POSTS',
    SORTED_BY_VOTE_SCORE: '-voteScore',
    SORTED_BY_DATE: '-timestamp'
};

export default constants;